# Generated by Django 4.1.5 on 2023-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7)),
                ('cor', models.CharField(max_length=20)),
            ],
        ),
    ]
