# Generated by Django 4.1.5 on 2023-01-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car_list',
            new_name='lista_de_carros',
        ),
    ]
