# Generated by Django 4.1.5 on 2023-01-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_car_list_lista_de_carros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_de_carros',
            old_name='id',
            new_name='id_carro',
        ),
    ]
