# Generated by Django 4.1.5 on 2023-01-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_lista_de_carros_id_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_de_carros',
            name='id_carro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
